// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp87dLEb3RV6BFYPlqtv5Rn_Vxiv7CbUE',
    appId: '1:989922588617:web:e7dd6ebacf1430eb969a18',
    messagingSenderId: '989922588617',
    projectId: 'tripsaathi-b1e9c',
    authDomain: 'tripsaathi-b1e9c.firebaseapp.com',
    storageBucket: 'tripsaathi-b1e9c.appspot.com',
    measurementId: 'G-8C3BHE0KPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4MY5nbx8OjBlWUNKahRw0cBT2Qoct_HA',
    appId: '1:989922588617:android:a2c655c7c900be57969a18',
    messagingSenderId: '989922588617',
    projectId: 'tripsaathi-b1e9c',
    storageBucket: 'tripsaathi-b1e9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOVWRB_6r3cKxza24O4OaMMojzZFPYEcs',
    appId: '1:989922588617:ios:5e54202c4f8631e7969a18',
    messagingSenderId: '989922588617',
    projectId: 'tripsaathi-b1e9c',
    storageBucket: 'tripsaathi-b1e9c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
